config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#index'

  resources :articles
  resources :users, except: [:new]

  get 'topstories', to: 'pages#topstories'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  # post 'users', to: 'users#create'
end  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    validates :title, presence: true
    validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    has_many :articles
    validates :username, presence: true, 
                            uniqueness: { case_sensitive: false }, 
                            length: { minimum: 3, maximum: 25 } 

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    
    validates :email, presence: true, 
                    uniqueness: { case_sensitive: false }, 
                    length: { maximum: 105 },
                    format: { with: VALID_EMAIL_REGEX }

    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in? 
        !!current_user
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
        @articles = Article.all
    end

    def show
        @article = Article.find(params[:id])
    end 

    def new
        @article = Article.new
    end

    def edit
        @article = Article.find params[:id]
    end

    def create
        @article = Article.new(article_params)
        @article.user = current_user
        respond_to do |format|
            if @article.save
            @article.save
                format.html { redirect_to @article, notice: 'Article was successfully created.' }
                format.json { render :show, status: :created, location: @article }
            else
                format.html { render :new}
                format.json { render json: @article.errors, status: :unprocessable_entity }
            end
        end
    end

    def update
        @article = Article.find params[:id]
        respond_to do |format|
            if @article.update(article_params)
                format.html { redirect_to @article, notice: 'Article was successfully updated.' }
                format.json { render :show, status: :ok, location: @article }
            else
                format.html { render :edit }
                format.json { render json: @article.errors, status: :unprocessable_entity }
            end
        end
    end

    def destroy
        @article = Article.find params[:id]
        @article.destroy
        respond_to do |format|
            format.html { redirect_to articles_url, notice: 'Article was successfully destroyed' }
            format.json { head :no_content } 
        end
    end

    private

        def set_article
            @article = Article.find(params[:id])
        end
        def article_params
            params.require(:article).permit(:title, :description, :excerpt)
        end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index
        redirect_to articles_path if logged_in?
    end

    def topstories
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:notice] = "Logged in successfully"
            redirect_to user
        else
            flash.now[:alert] = "Error logging in"
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:notice] = "Logged out"
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update]

    def index
        @users = User.all
    end
    def new
        @user = User.new
    end

    def show
        
    end 

    def edit
        
    end

    def update
        if @user.update(user_params)
            flash[:notice] = "Account Successfully updated"
            redirect_to articles_path
        else
            render 'edit'
        end 
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            flash[:notice] = "Welcome to Spacepress!, #{@user.username} sign up successful." 
            redirect_to users_path
        else
            render 'new'
        end 
    end

    private
    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

    def set_user
        @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %> 
    <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this users from being saved:</h2>

      <ul>
        <% article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :excerpt %>
    <%= form.text_field :excerpt %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %> 

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %>
<%= link_to 'Back', article_path %>

app/views/articles/index.html.erb
<h1>Articles Index</h1>

<table>
    <thead>
        <tr>Author</tr>
        <tr>Title</tr>
        <tr>Excerpt</tr>
        <tr>Description</tr>
    </thead>

    <tbody>
        <% @articles.each do |article| %>
            <tr>
                <% if article.user %>
                    <td><%= link_to article.user.username, user_path(article.user) %>
                <% end %>
                <td><%= article.title %></td>
                <td><%= article.excerpt %></td>  
                <td><%= article.description %></td> 
                <td><%= link_to 'Show', article %></td>
                <% if logged_in? && article.user == current_user %>
                    <td><%= link_to 'Edit', edit_article_path(article) %></td>
                    <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                <% end %>
            </tr>
        <% end %>
    </tbody>
</table>

<%= link_to 'Create new article', new_article_path %>

app/views/articles/new.html.erb
<h1>Create New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %> 

app/views/articles/show.html.erb
<h1>Showing article details</h1>
<p><strong>Author: <%= @article.user.username if @article.user %> </strong></p>
<p><strong>Title: <%= @article.title %> </strong></p>
<p><strong>description: <%= @article.description %></strong></p>

<% if user.logged_in? && @article.user == current_user %> 
    <td><%= link_to 'Edit', edit_article_path(@article) %></td>
    <td><%= link_to 'Destroy', article_path(@article), method: :delete, data: { confirm: 'Are you sure?' } %></td>
<% end %> 
<%= link_to 'Back', articles_path %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spacepress</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  <% if logged_in? %>
    <%= link_to 'Logout', logout_path, method: :delete %> | 
    <%= link_to current_user.username, user_path(current_user) %> 
  <% else %> 
    <%= link_to 'Login', login_path %> | <%= link_to "Sign up", signup_path %>
  <% end %>
  </body>
</html>

app/views/pages/index.html.erb
<h1>The Home Page.</h1>

app/views/pages/topstories.erb
<h1>Top Trending Stories</h1>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |form| %> 
    <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="actions">
    <%= form.submit(@user.new_record? ? "sign up" : "update account") %>
  </div>

<% end %> 

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %>

app/views/users/index.html.erb
<h1>Users Index</h1>

<table>
    <thead>
        <tr>Username</tr>
        <tr>Email</tr>
    </thead>

    <tbody>
        <% @users.each do |user| %>
            <tr>
                <td><%= user.username %>
                <td><%= user.email %></td>
                <td><%= link_to "View profile", user %></td>
                <% if logged_in? && user == current_user %>  
                    <td><%= link_to "Edit profile", edit_user_path(user) %></td>
                <% end %>
            </tr>
        <% end %>
    </tbody>
</table>

<%= link_to "Sign up", signup_path%>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'form', user: @user %>

 

app/views/users/show.html.erb
<h1>Showing user: <%= @user.username %></h1>
<p> email: <%= @user.email %></p>